server:
  port: 5000

spring:
  cloud:
    config:
      name: config
      server:
        git:
          uri: https://github.com/venkateshreddypala/aircraft
          search-paths: config-files*
  application:
    name: config